<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\AbujaSocialMetaverse.Shared.csproj" />
    <ProjectReference Include="..\..\Infrastructure\AbujaSocialMetaverse.Infrastructure.csproj" />
    <ProjectReference Include="..\CoreModule\AbujaSocialMetaverse.Modules.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
